### ISSUE TITLE
Unknown ruby installation type

### ISSUE THREAD

**Issue by balzdur** [bitrise-io/go-utils#111]
Hi there 👋 

I'm trying to debug my bitrise  build locally and I'm dealing with a problem concerning the type of ruby installation on my computer.

I make use of [`asdf`](https://asdf-vm.com/#/) as a meta version manager and thus, to controll ruby version.

Digging in code source I realised the issue is due to [this method](https://github.com/bitrise-io/go-utils/blob/6cc2aa4d248adef509996ac484bffd38856ddf80/command/rubycommand/rubycommand.go#L51) who do not take into account my version manager.

Could it be possible to add it ?

I am aware that not being a standard like `rbenv` or `rvm` it is not a priority but I ask just in case!

As an alternative, I would make use of `rvm` to debug locally my bitrise build.

**Comment by non-binary** [comment]
We are happy to review pull requests!
